title: CHI Learning & Development System (CHILD)
url: https://www.child.chi.sg
favicon: /images/chi logo.png
colors:
  primary-color: "#a6192e"
  secondary-color: "#a6192e"
  media-colors:
    - title: media-color-one
      color: "#a76f5e"
    - title: media-color-two
      color: "#bb372e"
    - title: media-color-three
      color: "#bc8885"
    - title: media-color-four
      color: "#9b9b9b"
    - title: media-color-five
      color: "#94795d"
description: CHILD aims to be an open resource to anyone in the world to access
  and contribute, and we envision for all players in health ecosystem to
  Share-Learn-Do.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d33f4rx9vjypzg.amplifyapp.com
prod: https://master.d33f4rx9vjypzg.amplifyapp.com
resources_name: learn-child-collection
shareicon: /images/chi logo.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
